service_name: '07042c7c-b34e-4337-8931-a8cf2504be6d'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://81fb-46-242-12-179.ngrok-free.app
  public_url: https://81fb-46-242-12-179.ngrok-free.app
  uc_flow:
    domain: https://uc-flow-v2-pp-api.uis.st
    jwt_secret: dsgdfdagg
